import { test, expect } from '@playwright/test'

test('admin, monthly report, account management and Ponto camera punch', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const mobile = testInfo.project.name === 'mobile'
  const username = `ponto-${testInfo.project.name}`
  const password = 'PontoE2E12345'
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Criar conta', exact: true })).toHaveCount(0)
  await page.getByLabel('Usuário ou e-mail').fill('admin')
  await page.getByLabel('Senha de acesso', { exact: true }).fill('AdminE2E12345')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Área administrativa' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Área administrativa' })).toBeVisible()
  await page.getByRole('button', { name: 'Relatórios', exact: true }).click()
  await page.getByLabel('Selecionar mês do pagamento').fill('2026-09')
  await expect(page.getByRole('heading', { name: 'Pagamento por funcionário' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Pagamento por funcionário' }).getByText('R$ 120,00', { exact: true }).first()).toBeVisible()
  for (const label of ['Planilha (Excel / Sheets)', 'Baixar PDF', 'CSV']) {
    const download = page.waitForEvent('download')
    await page.getByRole('button', { name: label, exact: true }).click()
    expect(await (await download).failure()).toBeNull()
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await expect(page.getByRole('button', { name: 'Planilha (Excel / Sheets)', exact: true })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('report.png'), fullPage: true })
  await page.getByRole('button', { name: 'Cadastros', exact: true }).click()
  await page.getByRole('button', { name: 'Cadastrar usuário Ponto', exact: true }).click()
  const accounts = page.locator('section').filter({ has: page.getByRole('button', { name: 'Criar conta Ponto', exact: true }) })
  await accounts.getByLabel('Usuário Ponto', { exact: true }).fill(username)
  await accounts.getByLabel('Senha', { exact: true }).fill(password)
  await accounts.getByRole('button', { name: 'Criar conta Ponto', exact: true }).click()
  await expect(accounts.getByRole('status')).toContainText('criada')
  const account = accounts.locator('div.rounded-xl').filter({ has: page.getByText(username, { exact: true }) })
  await account.getByRole('button', { name: 'Desativar', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Desativar', exact: true }).click()
  await expect(account.getByText('Desativada', { exact: true })).toBeVisible()
  await account.getByRole('button', { name: 'Reativar', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Reativar', exact: true }).click()
  await account.getByRole('button', { name: 'Redefinir senha', exact: true }).click()
  await page.getByLabel('Nova senha', { exact: true }).fill('PontoUpdated12345')
  await page.getByRole('dialog').getByRole('button', { name: 'Redefinir senha', exact: true }).click()
  await expect(accounts.getByRole('status')).toContainText('redefinida')
  await page.getByRole('button', { name: 'Sair da conta', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: /Sair/ }).click()
  await page.getByLabel('Usuário ou e-mail').fill(username)
  await page.getByLabel('Senha de acesso', { exact: true }).fill('PontoUpdated12345')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Digite seu PIN' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Digite seu PIN' })).toBeVisible()
  await page.getByLabel('PIN de 4 números').fill(mobile ? '5678' : '1234')
  await page.getByRole('button', { name: 'Marcar ponto', exact: true }).click()
  await expect(page.getByText(/Teste (Desktop|Mobile)/).first()).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('button', { name: 'Cadastros', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Sair', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Sair do terminal', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Entrar', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
